"""Basin-hopping wrapper around scipy's local optimizers.

Two methods are supported:

  - **COBYLA** (default, gradient-free) — for small parameter counts and
    when the objective is non-smooth. Cheap per iteration but scales
    poorly past ~50 parameters.

  - **L-BFGS-B with parameter-shift gradients** — for variational
    quantum circuits where every parametric gate is generated by a
    Pauli-like operator with eigenvalues ±1. The shift rule

       ∂<O>_ψ(θ) / ∂θ_i = ½ · ( <O>_ψ(θ + π/2 ê_i) − <O>_ψ(θ − π/2 ê_i) )

    is exact for all gates we support (RX/RY/RZ/RXX/RYY/RZZ). Two
    objective evaluations per parameter per gradient call, then L-BFGS-B
    converges in a handful of iterations — orders of magnitude better
    than gradient-free for moderate parameter counts.

Each call to `optimize` runs `basin_hops` independent restarts and
returns the best parameters found.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
from scipy.optimize import minimize

from quiver.config import OptimizerConfig


def parameter_shift_gradient(
    objective: Callable[[np.ndarray], float],
    params: np.ndarray,
    shift: float = np.pi / 2,
) -> np.ndarray:
    """Exact gradient via the parameter-shift rule. 2N objective calls
    where N is len(params). Caller's responsibility to ensure every
    parametric gate's generator has eigenvalues ±1 (true for all
    rotation gates Quiver uses)."""
    n = len(params)
    grad = np.zeros(n)
    for i in range(n):
        e = np.zeros(n)
        e[i] = shift
        f_plus = objective(params + e)
        f_minus = objective(params - e)
        grad[i] = 0.5 * (f_plus - f_minus)
    return grad


@dataclass
class OptimizeResult:
    params: np.ndarray
    objective: float
    nfev: int
    converged: bool


def _init_strategies(num_params: int, rng: np.random.Generator) -> list[np.ndarray]:
    """Diverse seeds: zero (good for variational identity), small Gaussian
    (perturbed identity), and full uniform random."""
    return [
        np.zeros(num_params),
        rng.normal(0.0, 0.1, size=num_params),
        rng.uniform(-np.pi, np.pi, size=num_params),
    ]


def optimize(
    objective: Callable[[np.ndarray], float],
    num_params: int,
    config: OptimizerConfig,
    rng: np.random.Generator,
    warm_start: np.ndarray | None = None,
) -> OptimizeResult:
    # Edge case: a fully non-parametric circuit (all gates fixed) — common
    # for mutated specs after deletes — has nothing to optimize.
    if num_params == 0:
        params = np.zeros(0)
        val = float(objective(params))
        return OptimizeResult(
            params=params, objective=val, nfev=1,
            converged=val < config.tolerance,
        )

    if warm_start is not None and len(warm_start) == num_params:
        # Mutation rounds: parent's verified params are usually a good
        # neighbourhood. Front-load the seed list with warm starts.
        warm = np.asarray(warm_start, dtype=float)
        seeds = [
            warm,
            warm + rng.normal(0.0, 0.1, size=num_params),
            warm + rng.normal(0.0, 0.5, size=num_params),
        ]
    else:
        seeds = _init_strategies(num_params, rng)
    best_params = seeds[0]
    best_val = float(objective(best_params))
    total_nfev = 1

    use_lbfgs = config.method.upper() in ("L-BFGS-B", "LBFGS", "LBFGSB")

    for hop in range(max(1, config.basin_hops)):
        if hop < len(seeds):
            x0 = seeds[hop]
        else:
            anneal = max(0.25, 1.0 - 0.05 * (hop - len(seeds)))
            scale = config.step_size * anneal
            x0 = best_params + rng.normal(0.0, scale, size=num_params)

        if use_lbfgs:
            jac = lambda p: parameter_shift_gradient(objective, p)
            result = minimize(
                objective, x0,
                method="L-BFGS-B",
                jac=jac,
                options={
                    "maxiter": max(20, config.max_iter // 4),
                    "ftol": config.tolerance,
                    "gtol": 1e-5,
                },
            )
            # L-BFGS-B's `nfev` doesn't include the gradient calls (which
            # internally invoke the objective 2N times each); add them.
            grad_calls = int(result.get("njev", 0)) if isinstance(result, dict) else int(getattr(result, "njev", 0))
            total_nfev += int(result.nfev) + grad_calls * 2 * num_params
        else:
            effective_max_iter = max(config.max_iter, num_params + 50)
            result = minimize(
                objective, x0,
                method=config.method,
                options={
                    "maxiter": effective_max_iter,
                    "rhobeg": 0.5,
                    "catol": config.tolerance,
                },
            )
            total_nfev += int(result.nfev)

        if float(result.fun) < best_val:
            best_val = float(result.fun)
            best_params = np.asarray(result.x)

        if best_val < config.tolerance:
            break

    return OptimizeResult(
        params=best_params,
        objective=best_val,
        nfev=total_nfev,
        converged=best_val < config.tolerance,
    )
